# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog
  adminer:
    network_mode: host
    image: adminer
    ports:
      - 8080:8080