# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    network_mode: host
    image: rust:1.49
    working_dir: /usr/src/myapp
    volumes:
        - .:/usr/src/myapp
    command: "cargo run"
    ports:
        - 3001:3001

